version: '2'
services:
    scm-app:
        image: scm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://scm-mysql:3306/scm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    scm-mysql:
        extends:
            file: mysql.yml
            service: scm-mysql
